### ISSUE TITLE
Remap <C-w> and also each resize command

### ISSUE THREAD

**Issue by p4-k4** [sedm0784/vim-resize-mode#1]
Hi there,

Is it possible to remap <C-w> and also each resize command?

For example:
For example, I want to use:
`<leader>w r` to trigger resize mode.
`h` - decrease width
`l` - increase width
`j` - decrease height
`k` - increase height

Thanks

**Comment by sedm0784** [comment]
Because Resize Mode is intended to be as transparent as possible, I'm afraid having separate mappings for entering the mode and resizing once in the mode isn't currently supported.

I'd be happy to add something like this as a feature request, but in the meantime, you might like to try [winresizer.vim](https://github.com/simeji/winresizer), which already works in this way.

**Comment by p4-k4** [comment]
Ah wow, that's exactly what I was after thank you.And totally understand wrt transparency. Cheers
